"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation data - completely separated by language
const translations = {
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.services": "خدماتنا",
    "nav.projects": "مشاريعنا",
    "nav.gallery": "معرض الأعمال", // Added gallery translation
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.getQuote": "احصل على عرض سعر",

    // Services dropdown
    "nav.services.residential": "البناء السكني",
    "nav.services.commercial": "التطوير التجاري",
    "nav.services.industrial": "المرافق الصناعية",
    "nav.services.design": "التصميم المعماري",
    "nav.services.luxury": "التشطيبات الفاخرة",
    "nav.services.brand": "الهوية التجارية",
    "nav.services.maintenance": "الصيانة والتجديدات",
    "nav.services.supplies": "التوريدات العامة",

    // Hero section
    "hero.badge": "شركة العزب للإنشاءات",
    "hero.title": "نحول أحلامكم إلى واقع",
    "hero.subtitle": "التميز في البناء والإنشاء",
    "hero.description":
      "نقدم خدمات البناء عالية الجودة للوحدات السكنية والتجارية والإدارية، مع التركيز على الجودة والأمان والمواد المستدامة",
    "hero.services": "خدماتنا",
    "hero.projects": "مشاريعنا",

    // About section
    "about.badge": "من نحن",
    "about.title": "سنقدم لك أفضل عمل حلمت به!",
    "about.subtitle": "خبرة تمتد لأكثر من عقد في مجال البناء والإنشاء",
    "about.description1":
      "في شركة العزب للإنشاءات، نحول الأفكار إلى واقع، من المفهوم إلى الإبداع، ونقدم لك أفضل عمل حلمت به من خلال خدمات البناء عالية الجودة للوحدات السكنية والتجارية والإدارية، مع التركيز على الجودة والأمان والمواد المستدامة",
    "about.description2":
      "نحن نؤمن بأن كل مشروع هو قصة نجاح جديدة، ونعمل بشغف لتحقيق رؤية عملائنا بأعلى معايير الجودة والاحترافية.",

    // Stats
    "stats.experience": "سنوات الخبرة",
    "stats.projects": "مشروع مكتمل",
    "stats.clients": "عميل راضي",
    "stats.workers": "عامل نشط",

    // Services section
    "services.badge": "خدماتنا",
    "services.title": "نقدم أفضل الخدمات",
    "services.subtitle": "خدمات شاملة في البناء والإنشاء بأعلى معايير الجودة والأمان",
    "services.building": "إنشاء المباني",
    "services.building.desc": "نقدم خدمات إنشاء المباني الشاملة، مع ضمان الجودة والأمان في كل مشروع",
    "services.renovation": "تجديد المنازل",
    "services.renovation.desc": "حول منزلك إلى منزل أحلامك مع حلول التجديد الكاملة لدينا",
    "services.design": "التصميم المعماري",
    "services.design.desc": "خدمات التصميم المعماري تجمع بين الإبداع والوظائف لتحقيق رؤيتك",
    "services.materials": "توريد المواد",
    "services.materials.desc": "نوفر مواد البناء عالية الجودة لدعم مشاريع البناء الخاصة بك",
    "services.consulting": "استشارات البناء",
    "services.consulting.desc": "احصل على مشورة الخبراء لمشاريع البناء الخاصة بك مع استشاريينا ذوي الخبرة",
    "services.interior": "التصميم الداخلي",
    "services.interior.desc": "خدمات التصميم الداخلي تجلب الأناقة والوظائف لأي مساحة، مصممة حسب تفضيلاتك",
    "services.viewAll": "عرض جميع الخدمات",

    // CTA section
    "cta.title": "هل أنت مستعد لبدء مشروع البناء الخاص بك؟",
    "cta.subtitle": "ابدأ رحلتك معنا اليوم",
    "cta.description": "اتصل بنا اليوم للحصول على استشارة مجانية وعرض أسعار. فريقنا مستعد لتحقيق رؤيتك بدقة وتميز.",
    "cta.freeQuote": "احصل على عرض أسعار مجاني",
    "cta.contactTeam": "اتصل بفريقنا",

    // Cost Calculator
    "calculator.title": "حاسبة التكلفة التقديرية",
    "calculator.subtitle": "احصل على تقدير أولي لتكلفة مشروعك",
    "calculator.projectType": "نوع المشروع",
    "calculator.projectType.residential": "سكني",
    "calculator.projectType.commercial": "تجاري",
    "calculator.projectType.industrial": "صناعي",
    "calculator.projectType.renovation": "تجديد",
    "calculator.area": "المساحة (متر مربع)",
    "calculator.finishType": "نوع التشطيب",
    "calculator.finishType.basic": "أساسي",
    "calculator.finishType.standard": "عادي",
    "calculator.finishType.luxury": "فاخر",
    "calculator.finishType.premium": "ممتاز",
    "calculator.floors": "عدد الطوابق",
    "calculator.location": "الموقع",
    "calculator.location.cairo": "القاهرة",
    "calculator.location.giza": "الجيزة",
    "calculator.location.alexandria": "الإسكندرية",
    "calculator.location.other": "أخرى",
    "calculator.calculate": "احسب التكلفة",
    "calculator.result.title": "التكلفة التقديرية",
    "calculator.result.total": "إجمالي التكلفة",
    "calculator.result.perMeter": "التكلفة لكل متر مربع",
    "calculator.result.note": "هذا تقدير أولي، للحصول على عرض سعر دقيق يرجى التواصل معنا",
    "calculator.result.contact": "احصل على عرض سعر دقيق",
    "calculator.reset": "إعادة تعيين",

    // Consultation Booking
    "booking.title": "حجز استشارة مجانية",
    "booking.subtitle": "احجز استشارة مجانية مع خبرائنا",
    "booking.description": "احصل على استشارة مجانية مع فريق الخبراء لدينا لمناقشة مشروعك والحصول على أفضل الحلول",
    "booking.form.personalInfo": "المعلومات الشخصية",
    "booking.form.name": "الاسم الكامل",
    "booking.form.email": "البريد الإلكتروني",
    "booking.form.phone": "رقم الهاتف",
    "booking.form.projectInfo": "معلومات المشروع",
    "booking.form.projectType": "نوع المشروع",
    "booking.form.budget": "الميزانية المتوقعة",
    "booking.form.budget.under100k": "أقل من 100,000 جنيه",
    "booking.form.budget.100k-500k": "100,000 - 500,000 جنيه",
    "booking.form.budget.500k-1m": "500,000 - 1,000,000 جنيه",
    "booking.form.budget.over1m": "أكثر من 1,000,000 جنيه",
    "booking.form.description": "وصف المشروع",
    "booking.form.schedulingInfo": "معلومات الموعد",
    "booking.form.preferredDate": "التاريخ المفضل",
    "booking.form.preferredTime": "الوقت المفضل",
    "booking.form.time.morning": "صباحاً (9:00 - 12:00)",
    "booking.form.time.afternoon": "بعد الظهر (12:00 - 15:00)",
    "booking.form.time.evening": "مساءً (15:00 - 18:00)",
    "booking.form.consultationType": "نوع الاستشارة",
    "booking.form.consultationType.office": "في المكتب",
    "booking.form.consultationType.site": "في الموقع",
    "booking.form.consultationType.online": "عبر الإنترنت",
    "booking.form.submit": "احجز الاستشارة",
    "booking.form.reset": "إعادة تعيين",
    "booking.success.title": "تم الحجز بنجاح!",
    "booking.success.message": "شكراً لك! تم حجز استشارتك بنجاح. سيتواصل معك فريقنا قريباً لتأكيد الموعد.",
    "booking.success.reference": "رقم المرجع",
    "booking.success.backHome": "العودة للرئيسية",

    // Project Tracking
    "tracking.title": "تتبع حالة المشروع",
    "tracking.subtitle": "تابع تقدم مشروعك في الوقت الفعلي",
    "tracking.description": "أدخل رقم المشروع أو رقم المرجع لعرض حالة مشروعك الحالية",
    "tracking.form.projectId": "رقم المشروع",
    "tracking.form.referenceId": "رقم المرجع",
    "tracking.form.search": "البحث عن المشروع",
    "tracking.form.placeholder": "أدخل رقم المشروع أو المرجع",
    "tracking.notFound.title": "المشروع غير موجود",
    "tracking.notFound.message": "لم نتمكن من العثور على مشروع بهذا الرقم. يرجى التحقق من الرقم والمحاولة مرة أخرى.",
    "tracking.notFound.contact": "اتصل بخدمة العملاء",
    "tracking.project.title": "معلومات المشروع",
    "tracking.project.name": "اسم المشروع",
    "tracking.project.type": "نوع المشروع",
    "tracking.project.location": "الموقع",
    "tracking.project.startDate": "تاريخ البدء",
    "tracking.project.expectedEnd": "التاريخ المتوقع للانتهاء",
    "tracking.project.progress": "نسبة الإنجاز",
    "tracking.project.manager": "مدير المشروع",
    "tracking.project.contact": "رقم التواصل",
    "tracking.stages.title": "مراحل المشروع",
    "tracking.stages.planning": "التخطيط والتصميم",
    "tracking.stages.permits": "التراخيص والموافقات",
    "tracking.stages.foundation": "أعمال الأساسات",
    "tracking.stages.structure": "الهيكل الإنشائي",
    "tracking.stages.finishing": "أعمال التشطيب",
    "tracking.stages.delivery": "التسليم النهائي",
    "tracking.status.completed": "مكتمل",
    "tracking.status.inProgress": "قيد التنفيذ",
    "tracking.status.pending": "في الانتظار",
    "tracking.status.delayed": "متأخر",
    "tracking.timeline.title": "الجدول الزمني",
    "tracking.timeline.started": "بدأ في",
    "tracking.timeline.expected": "متوقع الانتهاء",
    "tracking.timeline.completed": "اكتمل في",
    "tracking.gallery.title": "صور التقدم",
    "tracking.gallery.noImages": "لا توجد صور متاحة حالياً",
    "tracking.updates.title": "آخر التحديثات",
    "tracking.updates.noUpdates": "لا توجد تحديثات جديدة",
    "tracking.team.title": "فريق المشروع",
    "tracking.team.projectManager": "مدير المشروع",
    "tracking.team.engineer": "المهندس المسؤول",
    "tracking.team.supervisor": "المشرف",
    "tracking.team.contact": "للتواصل",

    // Maintenance Request Form
    "maintenance.title": "طلب صيانة معمارية",
    "maintenance.subtitle": "اطلب خدمة صيانة احترافية لمشروعك",
    "maintenance.description": "نقدم خدمات صيانة شاملة على مدار الساعة لضمان استمرارية وجودة مشاريعك",
    "maintenance.form.clientInfo": "معلومات العميل",
    "maintenance.form.name": "الاسم الكامل",
    "maintenance.form.phone": "رقم الهاتف",
    "maintenance.form.email": "البريد الإلكتروني",
    "maintenance.form.address": "العنوان",
    "maintenance.form.requestInfo": "معلومات الطلب",
    "maintenance.form.type": "نوع الصيانة",
    "maintenance.form.type.emergency": "طارئة",
    "maintenance.form.type.routine": "دورية",
    "maintenance.form.type.repair": "إصلاح",
    "maintenance.form.type.renovation": "تجديد",
    "maintenance.form.type.inspection": "فحص",
    "maintenance.form.priority": "مستوى الأولوية",
    "maintenance.form.priority.low": "منخفض",
    "maintenance.form.priority.medium": "متوسط",
    "maintenance.form.priority.high": "عالي",
    "maintenance.form.priority.urgent": "عاجل",
    "maintenance.form.category": "فئة المشكلة",
    "maintenance.form.category.structural": "إنشائية",
    "maintenance.form.category.electrical": "كهربائية",
    "maintenance.form.category.plumbing": "سباكة",
    "maintenance.form.category.hvac": "تكييف وتهوية",
    "maintenance.form.category.finishing": "تشطيبات",
    "maintenance.form.category.other": "أخرى",
    "maintenance.form.description": "وصف المشكلة",
    "maintenance.form.images": "صور المشكلة",
    "maintenance.form.images.upload": "رفع الصور",
    "maintenance.form.images.max": "حد أقصى 5 صور",
    "maintenance.form.schedulingInfo": "معلومات الجدولة",
    "maintenance.form.preferredDate": "التاريخ المفضل",
    "maintenance.form.preferredTime": "الوقت المفضل",
    "maintenance.form.time.morning": "صباحاً (8:00 - 12:00)",
    "maintenance.form.time.afternoon": "بعد الظهر (12:00 - 16:00)",
    "maintenance.form.time.evening": "مساءً (16:00 - 20:00)",
    "maintenance.form.time.anytime": "أي وقت",
    "maintenance.form.accessInfo": "معلومات الوصول",
    "maintenance.form.accessNotes": "ملاحظات الوصول",
    "maintenance.form.contactPerson": "شخص الاتصال في الموقع",
    "maintenance.form.contactPhone": "رقم هاتف الاتصال",
    "maintenance.form.submit": "إرسال طلب الصيانة",
    "maintenance.form.reset": "إعادة تعيين",
    "maintenance.success.title": "تم إرسال الطلب بنجاح!",
    "maintenance.success.message":
      "شكراً لك! تم استلام طلب الصيانة بنجاح. سيتواصل معك فريقنا خلال 24 ساعة لتأكيد الموعد.",
    "maintenance.success.reference": "رقم الطلب",
    "maintenance.success.emergency": "للحالات الطارئة اتصل على: +201004006620",
    "maintenance.success.backHome": "العودة للرئيسية",
    "maintenance.success.trackRequest": "تتبع الطلب",

    // Settings and Profile
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
    security: "الأمان",
    preferences: "التفضيلات",
    manageAccountSettings: "إدارة إعدادات الحساب",
    profileInformation: "معلومات الملف الشخصي",
    updateProfileInformation: "تحديث معلومات الملف الشخصي",
    changePhoto: "تغيير الصورة",
    photoRequirements: "JPG أو PNG، حد أقصى 2MB",
    fullName: "الاسم الكامل",
    enterFullName: "أدخل الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    enterPhone: "أدخل رقم الهاتف",
    position: "المنصب",
    enterPosition: "أدخل المنصب",
    saving: "جاري الحفظ...",
    saveChanges: "حفظ التغييرات",
    notificationSettings: "إعدادات الإشعارات",
    manageNotificationPreferences: "إدارة تفضيلات الإشعارات",
    emailNotifications: "إشعارات البريد الإلكتروني",
    receiveEmailUpdates: "تلقي تحديثات البريد الإلكتروني",
    projectUpdates: "تحديثات المشاريع",
    notifyProjectChanges: "إشعار بتغييرات المشاريع",
    maintenanceAlerts: "تنبيهات الصيانة",
    urgentMaintenanceNotifications: "إشعارات الصيانة العاجلة",
    securitySettings: "إعدادات الأمان",
    manageAccountSecurity: "إدارة أمان الحساب",
    changePassword: "تغيير كلمة المرور",
    updatePassword: "تحديث كلمة المرور",
    twoFactorAuth: "المصادقة الثنائية",
    enableTwoFactor: "تفعيل المصادقة الثنائية",
    customizeExperience: "تخصيص التجربة",
    language: "اللغة",
    currentLanguage: "اللغة الحالية",
    darkMode: "الوضع المظلم",
    enableDarkTheme: "تفعيل المظهر المظلم",

    // Authentication
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    signUp: "إنشاء حساب",
    welcome: "مرحباً",
    loginToAccount: "تسجيل الدخول إلى حسابك",
    createAccount: "إنشاء حساب جديد",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    signInHere: "سجل دخولك هنا",
    signUpHere: "أنشئ حساباً هنا",
    adminPanel: "لوحة التحكم",
    accessDenied: "الوصول مرفوض",
    pleaseLogin: "يرجى تسجيل الدخول للوصول إلى هذه الصفحة",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.gallery": "Gallery", // Added gallery translation
    "nav.about": "About Us",
    "nav.contact": "Contact",
    "nav.getQuote": "Get a Quote",

    // Services dropdown
    "nav.services.residential": "Residential Construction",
    "nav.services.commercial": "Commercial Development",
    "nav.services.industrial": "Industrial Facilities",
    "nav.services.design": "Architectural Design",
    "nav.services.luxury": "Luxury Finishing",
    "nav.services.brand": "Brand Identity",
    "nav.services.maintenance": "Maintenance & Renovations",
    "nav.services.supplies": "General Supplies",

    // Hero section
    "hero.badge": "Al-Azab Construction",
    "hero.title": "Making Dreams Come to Life",
    "hero.subtitle": "Excellence in Construction & Development",
    "hero.description":
      "We provide high-quality building services for residential, commercial, and administrative units, focusing on quality, safety, and sustainable materials",
    "hero.services": "Our Services",
    "hero.projects": "View Projects",

    // About section
    "about.badge": "About Us",
    "about.title": "We will provide you the best work which you dreamt for!",
    "about.subtitle": "Over a decade of experience in construction and development",
    "about.description1":
      "At Al-Azab Construction, we bring ideas to life, from concept to creation, providing you the best work you've dreamed of through high-quality building services for residential, commercial, and administrative units, focusing on quality, safety, and sustainable materials.",
    "about.description2":
      "We believe that every project is a new success story, and we work passionately to achieve our clients' vision with the highest standards of quality and professionalism.",

    // Stats
    "stats.experience": "Years Experience",
    "stats.projects": "Projects Completed",
    "stats.clients": "Satisfied Clients",
    "stats.workers": "Active Workers",

    // Services section
    "services.badge": "Our Services",
    "services.title": "We provide best services",
    "services.subtitle":
      "Comprehensive construction and development services with the highest quality and safety standards",
    "services.building": "Building Construction",
    "services.building.desc":
      "We provide comprehensive building construction services, ensuring quality and safety in every project",
    "services.renovation": "House Renovation",
    "services.renovation.desc": "Transform your house into your dream home with our complete renovation solutions",
    "services.design": "Architecture Design",
    "services.design.desc":
      "Architectural design services that blend creativity with functionality to realize your vision",
    "services.materials": "Material Supply",
    "services.materials.desc": "We supply high-quality building materials to support your construction projects",
    "services.consulting": "Construction Consultant",
    "services.consulting.desc": "Get expert advice for your construction projects with our experienced consultants",
    "services.interior": "Interior Design",
    "services.interior.desc":
      "Interior design services bring elegance and functionality to any space, tailored to your preferences",
    "services.viewAll": "View All Services",

    // CTA section
    "cta.title": "Ready to Start Your Construction Project?",
    "cta.subtitle": "Start your journey with us today",
    "cta.description":
      "Contact us today for a free consultation and quote. Our team is ready to bring your vision to life with precision and excellence.",
    "cta.freeQuote": "Get Free Quote",
    "cta.contactTeam": "Contact Team",

    // Cost Calculator
    "calculator.title": "Cost Calculator",
    "calculator.subtitle": "Get an initial estimate for your project cost",
    "calculator.projectType": "Project Type",
    "calculator.projectType.residential": "Residential",
    "calculator.projectType.commercial": "Commercial",
    "calculator.projectType.industrial": "Industrial",
    "calculator.projectType.renovation": "Renovation",
    "calculator.area": "Area (Square Meters)",
    "calculator.finishType": "Finish Type",
    "calculator.finishType.basic": "Basic",
    "calculator.finishType.standard": "Standard",
    "calculator.finishType.luxury": "Luxury",
    "calculator.finishType.premium": "Premium",
    "calculator.floors": "Number of Floors",
    "calculator.location": "Location",
    "calculator.location.cairo": "Cairo",
    "calculator.location.giza": "Giza",
    "calculator.location.alexandria": "Alexandria",
    "calculator.location.other": "Other",
    "calculator.calculate": "Calculate Cost",
    "calculator.result.title": "Estimated Cost",
    "calculator.result.total": "Total Cost",
    "calculator.result.perMeter": "Cost per Square Meter",
    "calculator.result.note": "This is an initial estimate. For an accurate quote, please contact us",
    "calculator.result.contact": "Get Accurate Quote",
    "calculator.reset": "Reset",

    // Consultation Booking
    "booking.title": "Book Free Consultation",
    "booking.subtitle": "Schedule a free consultation with our experts",
    "booking.description":
      "Get a free consultation with our expert team to discuss your project and get the best solutions",
    "booking.form.personalInfo": "Personal Information",
    "booking.form.name": "Full Name",
    "booking.form.email": "Email Address",
    "booking.form.phone": "Phone Number",
    "booking.form.projectInfo": "Project Information",
    "booking.form.projectType": "Project Type",
    "booking.form.budget": "Expected Budget",
    "booking.form.budget.under100k": "Under 100,000 EGP",
    "booking.form.budget.100k-500k": "100,000 - 500,000 EGP",
    "booking.form.budget.500k-1m": "500,000 - 1,000,000 EGP",
    "booking.form.budget.over1m": "Over 1,000,000 EGP",
    "booking.form.description": "Project Description",
    "booking.form.schedulingInfo": "Scheduling Information",
    "booking.form.preferredDate": "Preferred Date",
    "booking.form.preferredTime": "Preferred Time",
    "booking.form.time.morning": "Morning (8:00 - 12:00)",
    "booking.form.time.afternoon": "Afternoon (12:00 - 16:00)",
    "booking.form.time.evening": "Evening (16:00 - 20:00)",
    "booking.form.time.anytime": "Anytime",
    "booking.form.consultationType": "Consultation Type",
    "booking.form.consultationType.office": "At Office",
    "booking.form.consultationType.site": "On Site",
    "booking.form.consultationType.online": "Online",
    "booking.form.submit": "Book Consultation",
    "booking.form.reset": "Reset Form",
    "booking.success.title": "Booking Successful!",
    "booking.success.message":
      "Thank you! Your consultation has been booked successfully. Our team will contact you soon to confirm the appointment.",
    "booking.success.reference": "Reference Number",
    "booking.success.backHome": "Back to Home",

    // Project Tracking
    "tracking.title": "Project Status Tracking",
    "tracking.subtitle": "Track your project progress in real-time",
    "tracking.description": "Enter your project number or reference ID to view your current project status",
    "tracking.form.projectId": "Project Number",
    "tracking.form.referenceId": "Reference ID",
    "tracking.form.search": "Search Project",
    "tracking.form.placeholder": "Enter project number or reference ID",
    "tracking.notFound.title": "Project Not Found",
    "tracking.notFound.message": "We couldn't find a project with this number. Please check the number and try again.",
    "tracking.notFound.contact": "Contact Customer Service",
    "tracking.project.title": "Project Information",
    "tracking.project.name": "Project Name",
    "tracking.project.type": "Project Type",
    "tracking.project.location": "Location",
    "tracking.project.startDate": "Start Date",
    "tracking.project.expectedEnd": "Expected Completion",
    "tracking.project.progress": "Progress",
    "tracking.project.manager": "Project Manager",
    "tracking.project.contact": "Contact Number",
    "tracking.stages.title": "Project Stages",
    "tracking.stages.planning": "Planning & Design",
    "tracking.stages.permits": "Permits & Approvals",
    "tracking.stages.foundation": "Foundation Work",
    "tracking.stages.structure": "Structural Work",
    "tracking.stages.finishing": "Finishing Work",
    "tracking.stages.delivery": "Final Delivery",
    "tracking.status.completed": "Completed",
    "tracking.status.inProgress": "In Progress",
    "tracking.status.pending": "Pending",
    "tracking.status.delayed": "Delayed",
    "tracking.timeline.title": "Timeline",
    "tracking.timeline.started": "Started on",
    "tracking.timeline.expected": "Expected completion",
    "tracking.timeline.completed": "Completed on",
    "tracking.gallery.title": "Progress Photos",
    "tracking.gallery.noImages": "No images available currently",
    "tracking.updates.title": "Latest Updates",
    "tracking.updates.noUpdates": "No new updates",
    "tracking.team.title": "Project Team",
    "tracking.team.projectManager": "Project Manager",
    "tracking.team.engineer": "Responsible Engineer",
    "tracking.team.supervisor": "Supervisor",
    "tracking.team.contact": "Contact",

    // Maintenance Request Form
    "maintenance.title": "Maintenance Request",
    "maintenance.subtitle": "Request professional maintenance service for your project",
    "maintenance.description":
      "We provide comprehensive 24/7 maintenance services to ensure continuity and quality of your projects",
    "maintenance.form.clientInfo": "Client Information",
    "maintenance.form.name": "Full Name",
    "maintenance.form.phone": "Phone Number",
    "maintenance.form.email": "Email Address",
    "maintenance.form.address": "Address",
    "maintenance.form.requestInfo": "Request Information",
    "maintenance.form.type": "Maintenance Type",
    "maintenance.form.type.emergency": "Emergency",
    "maintenance.form.type.routine": "Routine",
    "maintenance.form.type.repair": "Repair",
    "maintenance.form.type.renovation": "Renovation",
    "maintenance.form.type.inspection": "Inspection",
    "maintenance.form.priority": "Priority Level",
    "maintenance.form.priority.low": "Low",
    "maintenance.form.priority.medium": "Medium",
    "maintenance.form.priority.high": "High",
    "maintenance.form.priority.urgent": "Urgent",
    "maintenance.form.category": "Issue Category",
    "maintenance.form.category.structural": "Structural",
    "maintenance.form.category.electrical": "Electrical",
    "maintenance.form.category.plumbing": "Plumbing",
    "maintenance.form.category.hvac": "HVAC",
    "maintenance.form.category.finishing": "Finishing",
    "maintenance.form.category.other": "Other",
    "maintenance.form.description": "Issue Description",
    "maintenance.form.images": "Issue Photos",
    "maintenance.form.images.upload": "Upload Photos",
    "maintenance.form.images.max": "Maximum 5 photos",
    "maintenance.form.schedulingInfo": "Scheduling Information",
    "maintenance.form.preferredDate": "Preferred Date",
    "maintenance.form.preferredTime": "Preferred Time",
    "maintenance.form.time.morning": "Morning (8:00 - 12:00)",
    "maintenance.form.time.afternoon": "Afternoon (12:00 - 16:00)",
    "maintenance.form.time.evening": "Evening (16:00 - 20:00)",
    "maintenance.form.time.anytime": "Anytime",
    "maintenance.form.accessInfo": "Access Information",
    "maintenance.form.accessNotes": "Access Notes",
    "maintenance.form.contactPerson": "On-site Contact Person",
    "maintenance.form.contactPhone": "Contact Phone Number",
    "maintenance.form.submit": "Submit Maintenance Request",
    "maintenance.form.reset": "Reset Form",
    "maintenance.success.title": "Request Submitted Successfully!",
    "maintenance.success.message":
      "Thank you! Your maintenance request has been received successfully. Our team will contact you within 24 hours to confirm the appointment.",
    "maintenance.success.reference": "Request Number",
    "maintenance.success.emergency": "For emergencies call: +201004006620",
    "maintenance.success.backHome": "Back to Home",
    "maintenance.success.trackRequest": "Track Request",

    // Settings and Profile
    settings: "Settings",
    profile: "Profile",
    notifications: "Notifications",
    security: "Security",
    preferences: "Preferences",
    manageAccountSettings: "Manage your account settings",
    profileInformation: "Profile Information",
    updateProfileInformation: "Update your profile information",
    changePhoto: "Change Photo",
    photoRequirements: "JPG or PNG, max 2MB",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    email: "Email",
    phone: "Phone",
    enterPhone: "Enter phone number",
    position: "Position",
    enterPosition: "Enter position",
    saving: "Saving...",
    saveChanges: "Save Changes",
    notificationSettings: "Notification Settings",
    manageNotificationPreferences: "Manage your notification preferences",
    emailNotifications: "Email Notifications",
    receiveEmailUpdates: "Receive email updates",
    projectUpdates: "Project Updates",
    notifyProjectChanges: "Notify about project changes",
    maintenanceAlerts: "Maintenance Alerts",
    urgentMaintenanceNotifications: "Urgent maintenance notifications",
    securitySettings: "Security Settings",
    manageAccountSecurity: "Manage your account security",
    changePassword: "Change Password",
    updatePassword: "Update Password",
    twoFactorAuth: "Two-Factor Authentication",
    enableTwoFactor: "Enable two-factor authentication",
    customizeExperience: "Customize your experience",
    language: "Language",
    currentLanguage: "Current Language",
    darkMode: "Dark Mode",
    enableDarkTheme: "Enable dark theme",

    // Authentication
    login: "Login",
    logout: "Logout",
    signUp: "Sign Up",
    welcome: "Welcome",
    loginToAccount: "Login to your account",
    createAccount: "Create a new account",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember me",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signInHere: "Sign in here",
    signUpHere: "Sign up here",
    adminPanel: "Admin Panel",
    accessDenied: "Access Denied",
    pleaseLogin: "Please login to access this page",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ar")

  // Load saved language preference
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "ar" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language preference and update document direction
  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.lang = language
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr"

    document.body.className = document.body.className.replace(/\b(rtl|ltr)\b/g, "")
    document.body.classList.add(language === "ar" ? "rtl" : "ltr")
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
