-- Insert sample projects for testing and preview
-- Al-Azab Construction Company Sample Projects

-- Sample Project 1: Luxury Residential Villa
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  challenges_ar,
  challenges_en,
  solutions_ar,
  solutions_en,
  specifications
) VALUES (
  'luxury-villa-riyadh',
  'فيلا سكنية فاخرة',
  'Luxury Residential Villa',
  'مشروع فيلا سكنية فاخرة بتصميم عصري يجمع بين الفخامة والراحة',
  'Luxury residential villa project with modern design combining elegance and comfort',
  'residential',
  'الرياض، المملكة العربية السعودية',
  'Riyadh, Saudi Arabia',
  18,
  2500000,
  'عائلة الأحمد',
  'Al-Ahmad Family',
  'completed',
  true,
  '/modern-villa-exterior.png',
  ARRAY['/modern-villa-exterior.png', '/modern-apartment-building.png', '/modern-commercial-building.png'],
  'مشروع فيلا سكنية فاخرة على مساحة 800 متر مربع، يتميز بتصميم معماري عصري يجمع بين الأصالة والحداثة. يشمل المشروع 5 غرف نوم رئيسية، صالات استقبال واسعة، مسبح خارجي، وحديقة منسقة.',
  'Luxury residential villa project spanning 800 square meters, featuring modern architectural design that combines authenticity and modernity. The project includes 5 master bedrooms, spacious reception halls, outdoor pool, and landscaped garden.',
  'التحدي الرئيسي كان في دمج التصميم العصري مع المتطلبات التقليدية للعائلة، بالإضافة إلى التعامل مع طبيعة الأرض المنحدرة.',
  'The main challenge was integrating modern design with the family''s traditional requirements, in addition to dealing with the sloped terrain.',
  'تم تطوير تصميم مخصص يحترم الخصوصية العائلية مع توفير مساحات عصرية. استخدمنا تقنيات هندسية متقدمة للتعامل مع انحدار الأرض وتحويله إلى ميزة جمالية.',
  'We developed a custom design that respects family privacy while providing modern spaces. We used advanced engineering techniques to handle the land slope and turn it into an aesthetic feature.',
  '{"area": "800 متر مربع", "floors": "طابقين", "bedrooms": "5 غرف", "bathrooms": "6 حمامات", "parking": "4 سيارات", "features": ["مسبح خارجي", "حديقة", "نظام منزل ذكي", "طاقة شمسية"]}'
);

-- Sample Project 2: Commercial Tower
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  specifications
) VALUES (
  'commercial-tower-jeddah',
  'برج تجاري متعدد الاستخدامات',
  'Multi-Purpose Commercial Tower',
  'برج تجاري حديث يضم مكاتب ومحلات تجارية بتصميم معماري مميز',
  'Modern commercial tower featuring offices and retail spaces with distinctive architectural design',
  'commercial',
  'جدة، المملكة العربية السعودية',
  'Jeddah, Saudi Arabia',
  24,
  15000000,
  'مجموعة الخليج للاستثمار',
  'Gulf Investment Group',
  'in_progress',
  true,
  '/modern-apartment-building.png',
  ARRAY['/modern-apartment-building.png', '/modern-commercial-building.png', '/construction-site.png'],
  'برج تجاري متعدد الاستخدامات بارتفاع 20 طابقاً، يوفر مساحات مكتبية حديثة ومحلات تجارية في الطوابق الأرضية. يتميز بواجهة زجاجية عصرية وأنظمة ذكية متطورة.',
  'Multi-purpose commercial tower with 20 floors, providing modern office spaces and retail shops on ground floors. Features a modern glass facade and advanced smart systems.',
  '{"area": "12000 متر مربع", "floors": "20 طابق", "offices": "80 مكتب", "retail": "15 محل", "parking": "200 موقف", "features": ["واجهة زجاجية", "مصاعد ذكية", "نظام BMS", "طاقة متجددة"]}'
);

-- Sample Project 3: Residential Complex
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  residential',
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  specifications
) VALUES (
  'residential-complex-dammam',
  'مجمع سكني متكامل',
  'Integrated Residential Complex',
  'مجمع سكني متكامل يضم 50 وحدة سكنية بمرافق وخدمات متنوعة',
  'Integrated residential complex featuring 50 housing units with diverse facilities and services',
  'residential',
  'الدمام، المملكة العربية السعودية',
  'Dammam, Saudi Arabia',
  30,
  25000000,
  'شركة التطوير العقاري',
  'Real Estate Development Company',
  'planning',
  false,
  '/modern-commercial-building.png',
  ARRAY['/modern-commercial-building.png', '/modern-villa-exterior.png', '/construction-site.png'],
  'مجمع سكني متكامل على مساحة 15000 متر مربع، يضم 50 وحدة سكنية متنوعة بين الشقق والفلل. يشمل المشروع حديقة مركزية، نادي رياضي، ومسابح مشتركة.',
  'Integrated residential complex spanning 15,000 square meters, featuring 50 diverse housing units including apartments and villas. The project includes a central garden, sports club, and shared pools.',
  '{"area": "15000 متر مربع", "units": "50 وحدة", "types": ["شقق", "فلل"], "amenities": ["حديقة مركزية", "نادي رياضي", "مسابح", "ملاعب أطفال"], "parking": "100 موقف"}'
);

-- Sample Project 4: Shopping Mall
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  specifications
) VALUES (
  'shopping-mall-makkah',
  'مركز تسوق عصري',
  'Modern Shopping Mall',
  'مركز تسوق عصري بمساحات تجارية متنوعة ومرافق ترفيهية',
  'Modern shopping mall with diverse retail spaces and entertainment facilities',
  'shops',
  'مكة المكرمة، المملكة العربية السعودية',
  'Makkah, Saudi Arabia',
  20,
  18000000,
  'مجموعة المراكز التجارية',
  'Shopping Centers Group',
  'completed',
  false,
  '/construction-site.png',
  ARRAY['/construction-site.png', '/modern-apartment-building.png'],
  'مركز تسوق عصري على 3 طوابق، يضم 120 محل تجاري ومطاعم ومنطقة ترفيهية للعائلات. يتميز بتصميم داخلي فاخر وأنظمة تكييف وإضاءة متطورة.',
  'Modern shopping mall spanning 3 floors, featuring 120 retail shops, restaurants, and family entertainment area. Distinguished by luxurious interior design and advanced air conditioning and lighting systems.',
  '{"area": "25000 متر مربع", "floors": "3 طوابق", "shops": "120 محل", "restaurants": "15 مطعم", "parking": "500 موقف", "features": ["منطقة ترفيهية", "سينما", "منطقة طعام"]}'
);

-- Sample Project 5: Hospital Construction
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  specifications
) VALUES (
  'hospital-construction-riyadh',
  'مستشفى تخصصي',
  'Specialized Hospital',
  'بناء مستشفى تخصصي بأحدث المعايير الطبية والتقنيات المتقدمة',
  'Construction of specialized hospital with latest medical standards and advanced technologies',
  'construction',
  'الرياض، المملكة العربية السعودية',
  'Riyadh, Saudi Arabia',
  36,
  50000000,
  'وزارة الصحة',
  'Ministry of Health',
  'in_progress',
  true,
  '/professional-man-portrait.png',
  ARRAY['/professional-man-portrait.png', '/construction-site.png'],
  'مشروع بناء مستشفى تخصصي بسعة 200 سرير، يشمل أقسام متعددة للعناية المركزة والجراحة والأشعة. مصمم وفق أحدث المعايير الطبية العالمية.',
  'Specialized hospital construction project with 200-bed capacity, including multiple departments for intensive care, surgery, and radiology. Designed according to latest international medical standards.',
  '{"area": "30000 متر مربع", "capacity": "200 سرير", "floors": "8 طوابق", "departments": ["عناية مركزة", "جراحة", "أشعة", "طوارئ"], "features": ["غرف عمليات متطورة", "أنظمة طبية ذكية", "مهبط طائرات"]}'
);

-- Sample Project 6: Maintenance Project
INSERT INTO projects (
  slug,
  title_ar,
  title_en,
  description_ar,
  description_en,
  category,
  location_ar,
  location_en,
  duration_months,
  budget,
  client_ar,
  client_en,
  status,
  featured,
  main_image,
  gallery_images,
  overview_ar,
  overview_en,
  specifications
) VALUES (
  'building-renovation-jeddah',
  'تجديد وصيانة مبنى إداري',
  'Office Building Renovation',
  'مشروع تجديد شامل لمبنى إداري قديم وتحويله إلى مبنى عصري',
  'Comprehensive renovation project for old office building transforming it into modern facility',
  'maintenance',
  'جدة، المملكة العربية السعودية',
  'Jeddah, Saudi Arabia',
  12,
  3000000,
  'شركة الأعمال المتحدة',
  'United Business Company',
  'completed',
  false,
  '/confident-businessman.png',
  ARRAY['/confident-businessman.png', '/modern-villa-exterior.png'],
  'مشروع تجديد شامل لمبنى إداري بني في الثمانينات، يشمل تحديث الواجهات، الأنظمة الكهربائية والميكانيكية، والتصميم الداخلي. تم تحويل المبنى إلى مساحة عمل عصرية.',
  'Comprehensive renovation of office building built in the 1980s, including facade updates, electrical and mechanical systems, and interior design. The building was transformed into a modern workspace.',
  '{"area": "5000 متر مربع", "floors": "6 طوابق", "scope": ["تجديد الواجهات", "تحديث الأنظمة", "تصميم داخلي جديد"], "features": ["كفاءة طاقة", "مساحات عمل مفتوحة", "تقنيات ذكية"]}'
);
